### ISSUE TITLE
[Editorial] terminology usage related to blank node mapping in normalized dataset

### ISSUE THREAD

**Issue by iherman** [w3c/rdf-canon#109]
At the moment, the [normalized dataset](https://w3c.github.io/rdf-canon/spec/#dfn-normalized-dataset) includes:

> the [canonical issuer](https://w3c.github.io/rdf-canon/spec/#dfn-canonical-issuer) — mapping identifiers in the input dataset to canonical identifiers

and this is what is returned at the end of the algorithm. Strictly speaking, that is an overkill. The [canonical issuer](https://w3c.github.io/rdf-canon/spec/#dfn-canonical-issuer) is defined to be an [identifier issuer](https://w3c.github.io/rdf-canon/spec/#dfn-identifier-issuer) which refers to a [BNode Identifier Issuer State](https://w3c.github.io/rdf-canon/spec/#bn-issuer-state) which includes additional information that is irrelevant to the caller of the algorithm. The only information that is of importance is a simply mapping from input bnode ids to the canonical ones (essentially the relevant [issued identifier map](https://w3c.github.io/rdf-canon/spec/#dfn-issued-identifiers-map)).

I propose to replace the canonical issuer reference in the normalized dataset to an issued identifiers map in the definition of the normalized dataset.

**Comment by dlongley** [comment]
Yes, we should just use the map from the canonical issuer.
