### ISSUE TITLE
Recording the canonicalization and hashing applied.

### ISSUE THREAD

**Issue by afs** [w3c/rdf-canon#11]
In the [meeting on 2022-10-12](https://www.w3.org/2022/10/12-rch-minutes.html), there was mention of needing to say which choices were made in generating the hash.

We already have the existing URDNA2015 as the canonicalization algorithm. Anything this working group does that makes any change to that will need to have a way to declare which algorithm was used to produce the resultant canonical form.

There may be good reasons for different hashing and signing algorithms.

We need a naming scheme of choices made, together with a way to transmit that information.

See #4 about the output of canonicalization.

**Comment by dlongley** [comment]
I think it's the responsibility of a container format to express hashing, signing, and canonicalization algorithm choices. It's our responsibility here to provide a name for the canonicalization algorithm, which will be done when issue #87 is closed. I recommend we close this issue on that basis.

**Comment by philarcher** [comment]
[Discussed in WG meeting 2023-06-13](https://www.w3.org/2023/06/13-rch-minutes) Naming has been discussed #87. No further discussion forthcoming so issue is being closed.
