### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by philarcher** [w3c/rdf-canon#110]
The Explainer document provides a good basis for the WG's work. However, during the evolution of the c14n spec, we have recognized further features that need to be documented. Therefore, the use cases section of the spec can usefully be filled with a reference to the explainer doc *plus* some text around the features around output formats and mappings.

**Comment by philarcher** [comment]
@gkellogg Are you able to provide some text around output formats and mappings that I can incorporate into the explainer please? Rough notes are sufficient, I can do the wordsmithing stuff but I need a bit of hand-holding to make sure the doc says the right thing. This, I hope, will also address the TAG review question around quads #118 as well as allowing me to finish tidying up the explainer.

**Comment by philarcher** [comment]
Initial updating of the text of the explainer can be seen at https://github.com/w3c/rch-explainer/pull/4

**Comment by gkellogg** [comment]
Fixed by #110.

**Comment by TallTed** [comment]
> [@gkellogg] Fixed by #110.

_This_ is #110. I think that should say "Fixed by #175"
