### ISSUE TITLE
Consider changing "path" terminology

### ISSUE THREAD

**Issue by gkellogg** [w3c/rdf-canon#113]
The 'path' terminology could also be changed to better indicate what a path is (a particular deterministic serialization for a subgraph/subdataset of nodes without globally-unique identifiers).

**Comment by gkellogg** [comment]
Also, from https://github.com/w3c/rdf-canon/issues/111:

> The definition here is of a gossip path, not some uniquely determined the gossip path. (Later, the URDNA2015 algorithm selects one gossip path, but the details of that is singled out are not found here.)

> At times the later text also seems to identify a gossip path (graph-theoretical object) with a string representing that gossip path. You may want to consider promoting that latter concept to something explicitly defined; it could make the exposition clearer.

**Comment by philarcher** [comment]
Discussed 2023-06-21. Ask that @dlongley address this in the spec and include a reference to the academic paper, therefore change to spec is minimal.

**Comment by dlongley** [comment]
I raised #134 to address this.
