### ISSUE TITLE
Changing the test references to rdfc10?

### ISSUE THREAD

**Issue by iherman** [w3c/rdf-canon#117]
I know it is a pain, because all the test reports should be re-generated, but... shouldn't we change the reference RDF documents in the test suite from `testXXX-urdna2015.nq` to `testXXX-rdfc10.nq`?

**Comment by gkellogg** [comment]
Yes, we should; it is something that can be scripted easily enough, though. Ideally, re-creating test reports is easy for implementations.

**Comment by iherman** [comment]
>  Ideally, re-creating test reports is easy for implementations.

Sure. My test harness has the naming scheme baked in, but it is easy to change.
