### ISSUE TITLE
Use of term "degree"

### ISSUE THREAD

**Issue by gkellogg** [w3c/rdf-canon#124]
From #111:

> This use of 'degree' is just plain wrong, although I fear it might be too deeply entrenched for you to consider changing. The standard meaning of 'degree' in the context of graphs is as a synonym of valency (number of incidences of edges to the vertex under consideration). The concept at play here is rather that of radius of the neighbourhood being considered. I suppose for bounded valency graphs you could arrive at the radius being the degree of the polynomial bound on the cardinality of the neighbourhood considered, but even that is a far-fetched choice of terminology; depth (as in 'recursion depth') seems more natural.

> However, the risk of confusion is probably low.

**Comment by dlongley** [comment]
Perhaps we can say that the terminology is related to "degrees of separation" and may be also understood as "radius" -- and that it doesn't refer to the valency / number of edges. If we need any fun informative links:

https://en.wikipedia.org/wiki/Six_Degrees_of_Kevin_Bacon
https://en.wikipedia.org/wiki/Six_degrees_of_separation
