### ISSUE TITLE
PR merge style

### ISSUE THREAD

**Issue by davidlehn** [w3c/rdf-canon#130]
I just now noticed the last few months of PRs are getting squash merged.  Is there a reason for this?  It's lossy and makes the combined commit messages difficult to understand.  Would others prefer linear history and only allowing rebase merging going forward?

**Comment by gkellogg** [comment]
I’ve been using squash merge when there are many meaningless commits to a PR. I believe it makes things clearer to have a single commit for the PR. Once the branch used for the PR is removed, it should not leave residue. The PR suggestions don’t leave to meaningful commits.
