### ISSUE TITLE
Should we really return the "input blank node identifiers map" as part of the algorithm?

### ISSUE THREAD

**Issue by iherman** [w3c/rdf-canon#132]
This is triggered by the discussion on #131, e.g., see @gkellogg's remark on https://github.com/w3c/rdf-canon/pull/131#issuecomment-1607899236:

> The **canonicalized dataset** is composed of the original RDF dataset, the **input blank node identifier map** and the **issued identifiers map**. I don't see how we can test the **input blank node identifiers map** as it maps blank nodes (not identifiers) to their identifiers. I'm open to suggestions, but I think what we have speaks to the dual purposes of the algorithm.

Thinking about it further: the c14n dataset, the identifier map (and the c14n form, not mentioned here) are clearly generated by the algorithm. So far, so good. 

However, the mapping from bnodes to their identifiers is highly implementation dependent or, to be more exact, it reflects the underlying RDF infrastructure. The mapping itself does ***not*** depend on the algorithm, on its behavior, or indeed its output. Put it another way: once the c14n dataset, as well as the identifier map, are available, _**the map does not provide any additional information on the output of the algorithm**_. (This is also why it is extremely unclear how one would test this thing beyond the tests that are already present.)

Hence my proposal: I think we should _**remove**_ the "input blank node identifiers map" from the output of the algorithm. 

@dlongley @davidlehn @gkellogg @yamdan

**Comment by dlongley** [comment]
I believe the input identifier map is auto-populated by the algorithm if it is not provided as an input itself (or if not fully populated) and this would be a reason to return it in the output.

**Comment by dlongley** [comment]
Perhaps a minimal way to test the input identifier map is to just confirm that every value in the map is present as a key in the issued identifiers map.

**Comment by gkellogg** [comment]
The only thing that would make sense to to serialize the blank node key would be its identifier, which is also its value. We could fold that into the map tests and say that in addition to the output map matching the expected result, the keys there are exactly the same as the values in the input map.

**Comment by gkellogg** [comment]
See https://github.com/w3c/rdf-canon/pull/131/commits/8f838026a92d7c804b2f4a8e0e577b792fe1aa63 in PR #131 which adds an additional requirement that the keys of the issued identifiers map exactly match the values of the input blank node identifier map.

**Comment by dlongley** [comment]
> The only thing that would make sense to to serialize the blank node key would be its identifier, which is also its value. We could fold that into the map tests and say that in addition to the output map matching the expected result, the keys there are exactly the same as the values in the input map.

+1 ... this is what I somewhat clumsily meant above, thanks, @gkellogg!

**Comment by iherman** [comment]
> I believe the input identifier map is auto-populated by the algorithm if it is not provided as an input itself (or if not fully populated) and this would be a reason to return it in the output.

I do not really understand what you want to say @dlongley. But I also see https://github.com/w3c/rdf-canon/issues/132#issuecomment-1610154875; is this what you meant?

However... this remark, and @gkellogg's proposed change, does not address my original statement, meaning that I do not see why the algorithm is required to return the `input blank node identifiers map` in the first place. This information can be deduced from the other outputs for any given RDF framework, and in most cases the map is a completely trivial thing anyway (both in RDF-JS or Python' RDFLib, the equivalent of `bnode => bnode.id` does the trick).

I have no problem adding the additional statement of @gkellogg in that test. But I would propose is to change step (7) in the core algorithm in §4.4.3 by removing the reference to the `input blank node identifer map` altogether as redundant.

**Comment by iherman** [comment]
> So, for example, if there's some implementation that passes in an "abstract dataset" where the "if possible" clause fails, then our bases are covered because that implementation should be able to use the "input blank node identifier map" to map the blank nodes in the abstract dataset to their "arbitrarily assigned identifiers" -- and from there, to their canonical ones in the "issued identifiers map".

Ok, however unlikely that situation is, I take your point. I will simply close the issue.
