### ISSUE TITLE
Testsuite manifest.ttl: Not existing mf:entries values

### ISSUE THREAD

**Issue by Tpt** [w3c/rdf-canon#140]
In the testsuite `manifest.ttl`, some values in the `mf:entries` list are not defined as tests like `:test001m`. I believe `mk_manifest.rb` is not properly checking that tests are existing when building the `mf:entries` list.

**Comment by gkellogg** [comment]
Thanks, a script issue corrected in #141; the JSON-LD version of the manifest didn't contain these entries.
