### ISSUE TITLE
"Logging" expandos have empty context

### ISSUE THREAD

**Issue by davidlehn** [w3c/rdf-canon#147]
The "Logging" content is in the spec in commented sections, but show up as empty box in the spec.

Is a more in depth explanation needed for how to interpret that logging content?

**Comment by gkellogg** [comment]
Can you give a specific example with a URL to the fragment you don't see? The ones I looked at render properly for me.

**Comment by davidlehn** [comment]
All of them for me.  Expanding the "Logging" button only shows a empty box.  Chrome 112 in regular and incognito mode. 
 There a respec-highlight preload warning in console about it not being used within a few seconds.  May be related.
https://w3c.github.io/rdf-canon/spec/#typo-conventions
https://w3c.github.io/rdf-canon/spec/#canon-algo-algo

**Comment by gkellogg** [comment]
I see the problem in Chrome; works in Safari. I'll look into it.
