### ISSUE TITLE
"9.3 Dataset with Blank Node Named Graph" image vs text

### ISSUE THREAD

**Issue by davidlehn** [w3c/rdf-canon#149]
The "9.3 Dataset with Blank Node Named Graph" image doesn't match the following text.
- Image g0 has "Foo", text has "Bar".
- Image g0 has e2, text has another e0.

**Comment by peacekeeper** [comment]
I agree, this doesn't match. My guess is that the text is correct, and the image needs to be updated.

**Comment by gkellogg** [comment]
Accidentally pushed this to "main". @davidlehn if you continue to notice an issue, please re-open and I'll fix. Source for figure is https://docs.google.com/drawings/d/1g668zXf7ZgfByDeK6vW-uO6MvzpBCz7I0NtGd9xZao4.

**Comment by peacekeeper** [comment]
Thanks for addressing this so quickly.
