### ISSUE TITLE
\u vs \U

### ISSUE THREAD

**Issue by pfps** [w3c/rdf-canon#165]
"Characters in the range from U+0000 to U+001F and U+007F (DEL) that are not represented using [ECHAR](https://www.w3.org/TR/n-quads/#grammar-production-ECHAR) MUST be represented by [UCHAR](https://www.w3.org/TR/n-quads/#grammar-production-UCHAR)."

It appears to me that U+1 can be written as either \u0001 or \U00000001.

**Comment by TallTed** [comment]
That appears to be the case for all `\u0000`–`\uFFFF`, that they can also be written as `\U00000000`–`\U0000FFFF`, respectively. That does pose a quandary.

**Comment by gkellogg** [comment]
This does require clarification. Perhaps with something like “using the shortest possible ECHAR representation”. It would want some tests, too.
