### ISSUE TITLE
Test Report issues

### ISSUE THREAD

**Issue by davidlehn** [w3c/rdf-canon#168]
- Report is not well linked to and could be difficult to find.  Only link is from https://github.com/w3c/rdf-canon?  Would be good to perhaps also link from https://w3c.github.io/rdf-canon/tests/?
- Test table has 404 manifest links like https://w3c.github.io/rdf-canon/tests/manifest#test001c.  Should be https://w3c.github.io/rdf-canon/tests/#test001c.
- Subject compliance result table has an empty first cell.

**Comment by gkellogg** [comment]
Should probably be linked from the home page as well as the spec.

There was a build error, maybe related to Actions triggering on main, but that shouldn’t result in new errors introduced. Other issues require further investigation.
