### ISSUE TITLE
[spec] Unnecessary Yaml in preferences

### ISSUE THREAD

**Issue by domel** [w3c/rdf-canon#181]
In the spec the last item in References is Yaml, which is not used in the spec.

**Comment by gkellogg** [comment]
It actually is used in the spec, as we use YAML for showing logging. However, the log (and the [explanation of logging](https://www.w3.org/TR/rdf-canon/#informative-references)) get hidden in details. If you expand the Logging summary under its definition, you'll find the reference to [YAML].

**Comment by philarcher** [comment]
This looks resolved?
