### ISSUE TITLE
Sophia EARL results not in generated report.

### ISSUE THREAD

**Issue by davidlehn** [w3c/rdf-canon#185]
The Sophia implementation data (`./reports/rust-sophia-rdfc10.ttl`) results in many incorrect "untested" results in the generated EARL data, a SPARQL warning when the report generator process is run, and no results in the HTML report.

**Comment by pchampin** [comment]
I believe I located the problem :
the earl:subject of the assertions is *not* the doap:Project instance, but a specific doap:release of that instance...

I can fix this, but I find it actually more accurate :)
May be the code generating the report could be improved to accept this pattern?
I believe it is based on SPARQL queries, so replacing the predicate `earl:subject` with the path `earl:subject/^doap:release?` would do the trick (it would support both kind of assertions : those pointing to the project, and those pointing to a release).

**Comment by gkellogg** [comment]
Some queries can be customized in a configuration file, but I'm not sure that extends to the expected earl:subject. But, I'll look into it to see how it might cope.

**Comment by gkellogg** [comment]
So, looking into it, too much of the reporting infrastructure depends on the test subject being the `earl:Project`, not the Release. Although a couple of queries could be changed to produce results, it can't feasibly be updated to take either a Project or a Release.

The second problem is that the EARL namespace is ` <http://www.w3.org/ns/earl#>` not ` <https://www.w3.org/ns/earl#>`.

I'll make these to changes in the repository and do a PR for an update.

**Comment by pchampin** [comment]
> So, looking into it, too much of the reporting infrastructure depends on the test subject being the `earl:Project`, not the Release. Although a couple of queries could be changed to produce results, it can't feasibly be updated to take either a Project or a Release.

ok, I will fix my EARL report generator to do this, then

> The second problem is that the EARL namespace is ` <http://www.w3.org/ns/earl#>` not ` <https://www.w3.org/ns/earl#>`.

oops, sorry :fearful: 

> I'll make these to changes in the repository and do a PR for an update.

thanks
