### ISSUE TITLE
RDF Star

### ISSUE THREAD

**Issue by philarcher** [w3c/rdf-canon#2]
This is just a placeholder for a future discussion on what, if anything, the c14n spec will do about RDF Star (i.e. can an RDF star dataset be canonicalized?)

**Comment by philarcher** [comment]
On 2023-03-15 we discussed the issue of handling RDF star, in particular quoted triples. One possible proposed resolution was "The input of the c14n algorithm is an RDF Dataset as defined in RDF 1.1, which may be derived from pre-processing of later versions of RDF" but there's a feeling that the RDF* WG needs to be the ones to define terms for what is an RDF Dataset (or rather any changes to the existing ones). See the minutes at https://www.w3.org/2023/03/15-rch-minutes.html for more.

We're almost there, but not quite it seems.

**Comment by peacekeeper** [comment]
I think I understand the problem.. If RDF* changes the definition of what "RDF Dataset" means, then that sounds like it would have complex implications on what we're doing here.

But if OTOH the RDF* work can be mapped/transformed into an RDF 1.1 Dataset (using the "unstar" operation? sorry I'm not so familiary with this), then this would simply be a "pre-processing" step before our algorithm, and everything would be quite straightforward?

**Comment by gkellogg** [comment]
(Note, that it is `RDF-star`, not `RDF*`. `RDF*` was the name of Olaf's original paper; the CG and WG normalized the term as `RDF-star`.

To reiterate my comments on this, using "RDF 1.1 Dataset" is still inadequate, and it really should be something like "Classic RDF Dataset" as potentially defined in RDF 1.2, as such a dataset would not include `quoted triples` but could include language-tagged strings (literals) containing an additional `text direction` component, which is also something that RDF Canonicalization  needs. See https://github.com/w3c/rdf-concepts/issues/9 and https://github.com/w3c/rdf-star-wg/issues/33.

**Comment by philarcher** [comment]
This will be discussed in the Explainer doc (agreed 2023-09-11)

**Comment by philarcher** [comment]
Flagged as 'future work' since May 2023. No need to keep this open here.
