### ISSUE TITLE
SHACL/ShEx

### ISSUE THREAD

**Issue by philarcher** [w3c/rdf-canon#3]
An idea that has been discussed informally is that c14n of a dataset can be carried out against a specified shape. Doing so might have advantages:
* reducing, if not eliminating, the possibility of edge cases that cannot be computed in polynomial time;
* rejecting any additional triples that may be present in the original dataset.

**Comment by ericprud** [comment]
If you provide some sample (strawman) data, I can provide a schema (equally composed of straw). The cost of iterating is very low so feel free to drop in as rough a sketch as you have.

**Comment by gkellogg** [comment]
Note that both SHACL and ShEx will need support for datasets, not just graphs, for this to be generally applicable. Something they really should have, anyway. But this may require some work in RDF-star on dataset semantics, at least to relate the use of identifiers used as both graph names and subjects/objects having a semantic relationship, which is certainly assumed by Verifiable Claims and supported in JSON-LD.

**Comment by philarcher** [comment]
Given the above and the discussion in the group I am happy for this to be closed with no action.
