### ISSUE TITLE
Algorithm explanation

### ISSUE THREAD

**Issue by iherman** [w3c/rdf-canon#34]
This is a purely editorial comment.

Matt Garrish and I, co-editors of some publishing specs, have used the `<details>` elements to annotate the algorithmic descriptions. You can see an example in the [publication manifest](https://www.w3.org/TR/pub-manifest/#processing-algorithm) and the [EPUB 3](https://www.w3.org/TR/epub-33/#sec-container-iri). Obviously, the explanations are informational. We got extremely positive feedback of this approach; I wonder whether it is possible to do the same in the rdf-canon spec. I realize it is a lot of additional work, but I believe it is worth it on the long run...

cc @gkellogg @yamdan @dlongley

**Comment by gkellogg** [comment]
IIRC, @pchampin suggested using `<details>` in the JSON-LD algorithms, although not for inserting explanations. I added some Overview sections that distill some of the explanations prior to the Algorithm sub-section. Would you see the details replacing this, duplicating this, or doing something different?

I certainly support doing whatever we can to add some intuition to algorithm text to properly motivate and explain what the intention of the various steps are.

**Comment by iherman** [comment]
I do not see the examples you are referring to, @gkellogg. But, in any case, I believe I am talking about something different or, shall we say, extra: intertwining explanation within the algorithmic code itself. After all, the code lines are almost a reverse engineering of a real code in some programming language;  I am talking about good comments in the code, so to say. This is what the aforementioned publication specs do.
