### ISSUE TITLE
Spell out _identifier_ in the main algorithm (editorial)

### ISSUE THREAD

**Issue by iherman** [w3c/rdf-canon#38]
In [§4.5.2, point 5.4.2](https://w3c.github.io/rdf-canon/spec/#canon-algo-algo) defines, as part of the sentence, the _identifier_ variable. This value is used and important in later steps, so I think it would be better to call out its creation (as the first, and in this case only, value of the _identifier list_) in a separate step.

**Comment by iherman** [comment]
I have the impression that this comment has become moot with the recent changes on the spec...

**Comment by gkellogg** [comment]
As you created the issue, if you're satisfied, it can be closed. Thanks.
