### ISSUE TITLE
Some comments on the algorithmic sections

### ISSUE THREAD

**Issue by iherman** [w3c/rdf-canon#41]
- The [main algorithm](https://w3c.github.io/rdf-canon/spec/#canon-algo-algo) creates, in (3), a non-normalized identifier list. However, apart from the fact that entries may be removed from it in 5.3, this list is not used. The problematic cases, in step (6) are retrieved based on the hash->bnode[] map, which is also pruned in step 5.4 to remove the simple cases.
 
    Is this a bug somewhere or just an oversight and that list is not necessary?

- The [Hash N-degre Quads algorithm](https://w3c.github.io/rdf-canon/spec/#hash-nd-quads-algorithm) is defined with a set of specific input parameters (canonicalization `state`, the `identifier` for the blank node, and an `identifier issuer`). However, there is no clear statement in 6.2.4 of [the main algorithm](https://w3c.github.io/rdf-canon/spec/#canon-algo-algo) on exactly what parameter is used, especially for the the `identifier` which simply refers to the temporary issuer. The fact that the canonicalization state should be given (the one created in step 1) is fairly obvious but, for example, it is not clear whether the input to the algorithm should be `b_n` or `n`. (I presume it is `n`).

    In general, if we define the various algorithms in a functional style (which is fine) then we have to check whether the call of the algorithms follows the same thing, or whether we rely on some "global" values like the canonicalization state.

- Actually... the value of `b_n` in the same step (ie, in 6.2.3 of [the main algorithm](https://w3c.github.io/rdf-canon/spec/#canon-algo-algo)) isn't used anywhere. I presume that only the "side effect" is used, i.e., that the temporary issues will have a value for `n` (and may be reused later). If so, we should not assign the value to a variable at this point.

As a more general remark, the explanation/overview in the [Hash N-Degree Quad](https://w3c.github.io/rdf-canon/spec/#hash-nd-quads-overview) uses different terms, names, etc, then in the real algorithmic part. As a consequence, it really does not help to understand what is happening. 

I believe we should have real examples that show, step by step, what is happening in the [algorithm itself](https://w3c.github.io/rdf-canon/spec/#hash-nd-quads-algorithm) to help understanding this. To be honest, I converted the (semi-)English text into code but I would not say I understand what is really happening…

**Comment by gkellogg** [comment]
> As a more general remark, the explanation/overview in the [Hash N-Degree Quad](https://w3c.github.io/rdf-canon/spec/#hash-nd-quads-overview) uses different terms, names, etc, then in the real algorithmic part. As a consequence, it really does not help to understand what is happening.

We can work on aligning terms further; I did this elsewhere, but obviously not comprehensively.

> I believe we should have real examples that show, step by step, what is happening in the [algorithm itself](https://w3c.github.io/rdf-canon/spec/#hash-nd-quads-algorithm) to help understanding this. To be honest, I converted the (semi-)English text into code but I would not say I understand what is really happening…

I've started on examples, and am working on running the examples through all the algorithms to illustrate the behavior, Obviously, it gets more complicated when there's more branching. Feedback on the style of the existing examples would be useful, to know if they are helpful, or overly verbose.

As for the rest of your concerns, consider them on the list.

**Comment by iherman** [comment]
Thanks @gkellogg, I am looking forward to the example!

**Comment by iherman** [comment]
I guess #64 is covering this issue by now. If that is closed, this issue can also be closed.
