### ISSUE TITLE
Inconsistency between figure and text in the shared hashes example

### ISSUE THREAD

**Issue by yamdan** [w3c/rdf-canon#44]
Figure 2 in Example 3 actually illustrates
```
_:b0 :q :p .
_:b1 :q :p .
_:b2 :p _:b0 .
_:b3 :p _:b1 .
_:b2 :r _:b3 .
```
that is different from the current description:
```
:p :q _:b0 .
:p :q _:b1 .
_:b0 :p _:b2 .
_:b1 :p _:b3 .
_:b2 :r _:b3 .
```

It seems to me that fixing SVG figure is easier than fixing texts and hash values. Could I redraw the Figure 2?

**Comment by gkellogg** [comment]
Yeah, the arrows are backwards. The source of the SVG, as noted in the document, is https://docs.google.com/drawings/d/1HWpz8S-PNaWi02-utF62HAMd_0b-AF_tHNSRRUQILbU. Of course, both of these figures are fairly basic, and if you have a more artistic bent, then I'm sure they can be improved.

**Comment by gkellogg** [comment]
Fixed in https://github.com/w3c/rdf-canon/pull/43/commits/979593aef609482b48e7ce07082966c614415993, part of PR #42.
