### ISSUE TITLE
Add link to Editor's Draft from Github sidebar

### ISSUE THREAD

**Issue by msporny** [w3c/rdf-canon#50]
Please add a link to the spec from the Github side-bar. Example here:

![image](https://user-images.githubusercontent.com/108611/205651054-4599780a-e8a0-4be0-b326-2117a797516e.png)

I realize that we do have a link to the spec in the README.md, but that requires reading (and not depending on Github muscle memory). We should link to the spec from the side bar (and keep the link in the README.md) to make it easier to get to for those that are used to useful links on the Github side bar for other projects:

https://w3c.github.io/rdf-canon/spec/

**Comment by gkellogg** [comment]
I believe this is complete now, unless I misunderstood the link you were looking for.

**Comment by msporny** [comment]
> I believe this is complete now

Yes, it is. Thank you!
