### ISSUE TITLE
Duplicate test cases

### ISSUE THREAD

**Issue by yamdan** [w3c/rdf-canon#67]
Some test cases have identical inputs (`*-in.nq`) and outputs (`-urdna2015.nq`) to each other.
They can be grouped as follows (for example, [test024-in.nq](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test024-in.nq) is identical to [test025-in.nq](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test025-in.nq); [test024-urdna2015.nq](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test024-urdna2015.nq) is the same as [test025-urdna2015.nq](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test025-urdna2015.nq))

- [024](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test024) ([in](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test024-in.nq)/ [out](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test024-urdna2015.nq)), [025](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test025) ([in](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test025-in.nq) / [out](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test025-urdna2015.nq)), [026](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test026) ([in](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test026-in.nq) / [out](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test026-urdna2015.nq)), [027](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test027) ([in](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test027-in.nq) / [out](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test027-urdna2015.nq)), [028](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test028) ([in](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test028-in.nq) / [out](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test028-urdna2015.nq)), [029](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test029) ([in](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test029-in.nq) / [out](https://github.com/w3c/rdf-canon/blob/4bbba31db202118701af914c73d01335dbb1114f/tests/urdna2015/test029-urdna2015.nq))
- [031](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test031), [032](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test032)
- [033](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test033), [034](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test034)
- [035](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test035), [036](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test036), [037](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test037)
- [040](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test040), [041](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test041), [042](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test042) (fixed; I originally wrongly noted as 041, 042, 043)

It seems they originally came from distinct JSON-LD documents that resulted in the same sorted N-Quads. We can repair some of them to reflect the original intent of each test case. For example, in the case of 024-029:

test024-in.nq (original): "blank node - double circle of 3 (1-2-3)[^1]"
```
_:e0 <http://example.org/vocab#next> _:e1 .
_:e0 <http://example.org/vocab#prev> _:e2 .
_:e1 <http://example.org/vocab#next> _:e2 .
_:e1 <http://example.org/vocab#prev> _:e0 .
_:e2 <http://example.org/vocab#next> _:e0 .
_:e2 <http://example.org/vocab#prev> _:e1 .
```

test025-in.nq (updated): "blank node - double circle of 3 (1-3-2)"
```
_:e0 <http://example.org/vocab#next> _:e2 .
_:e0 <http://example.org/vocab#prev> _:e1 .
_:e2 <http://example.org/vocab#next> _:e1 .
_:e2 <http://example.org/vocab#prev> _:e0 .
_:e1 <http://example.org/vocab#next> _:e0 .
_:e1 <http://example.org/vocab#prev> _:e2 .
```

test026-in.nq (updated): "blank node - double circle of 3 (2-1-3)"
```
_:e1 <http://example.org/vocab#next> _:e0 .
_:e1 <http://example.org/vocab#prev> _:e2 .
_:e0 <http://example.org/vocab#next> _:e2 .
_:e0 <http://example.org/vocab#prev> _:e1 .
_:e2 <http://example.org/vocab#next> _:e1 .
_:e2 <http://example.org/vocab#prev> _:e0 .
```
(027-029 are omitted)

I checked that my implementation [passed](https://github.com/yamdan/rdf-canon-rust/commit/85c9d4af7e4b5c47f10f229f9637e1468fe0e5e0) the updated test024-029.

If I can confirm this is not my misunderstanding, I would like to create a PR that includes other test cases.

[^1]: from the description in [024](https://w3c.github.io/rdf-canon/tests/#manifest-urdna2015#test024), which should be renamed as "0-1-2" to be more understandable.

**Comment by gkellogg** [comment]
@dlongley would know, but I'm sure you're right that these were derived from JSON-LD inputs, that might have had a different form, but generated the same N-Quads. We should consolidate such duplicates.

**Comment by gkellogg** [comment]
@yamdan, do you want to take on consolidating and re-generating the manifests? They're driven from the manifest.csv file with a `mk_manifest.rb` script that updates the Turtle, JSON-LD and HTML versions of the manifests.

There's also a FIXME in the README.md that needs to be addressed.

**Comment by yamdan** [comment]
@gkellogg Thanks for letting me know the procedure. I will try to do that, while it may take a little longer since I will be at a conference whole next week.

**Comment by gkellogg** [comment]
No rush, and happy to help, but it would be good to spread the working knowledge of doing this kind of work.

**Comment by dlongley** [comment]
There were a number of tests that were intended to either shuffle the input order of the N-Quads or they shuffled the blank node identifiers used but retained the shape of the graph. If those changes have been lost we do want to restore them, and hopefully the names of the tests allow us to do that easily.

**Comment by gkellogg** [comment]
It can certainly be compared in GitHub to what came over from the CG. I think we just did a comprehensive change for `_:bxxx` to `_:exxx` (with an original `_:bxxx` form retained in a copy) as it was confusing when running a trace as `_:b` is a prefix used for temporary labels. Shouldn't have done any re-shuffling.

When the inputs were JSON-LD (maybe still captured in the CG repo?) there could have been some potential for things to be lost. Deeper history is in https://github.com/w3c-ccg/rdf-dataset-canonicalization (specifically [commit 48e1882b5c431224b31d3938231e517c867fa90e](https://github.com/w3c-ccg/rdf-dataset-canonicalization/commit/48e1882b5c431224b31d3938231e517c867fa90e)). But, I don't see any commits that had JSON-LD inputs to tests.

Running sha256sum on the original test inputs does show some duplicated files:

```
0b35a842886c838d5bb44bdf77c293974db401a23df3cfef0ea133a40ee18d96  test051-in.nq
0bd49519a05f9097d06360b4b68e184afe415d82f65b2f21f5dc689ce174317d  test017-in.nq
1a87060cb6b66e60264a278a99b9150ff1cd7e6a06ff50236fd0f82b86c65192  test035-in.nq
1a87060cb6b66e60264a278a99b9150ff1cd7e6a06ff50236fd0f82b86c65192  test036-in.nq
1a87060cb6b66e60264a278a99b9150ff1cd7e6a06ff50236fd0f82b86c65192  test037-in.nq
1fcc2848b4ff46225aaed2233347a3e2f5977e0d1a46f9fc8334b15fc1a7248f  test043-in.nq
2335e9c7da53d3018b2012d723a93caab9efebf661b05c1b18f37ab2e71310cc  test010-in.nq
23a4054292cf9cd75766646ab65f707568d908baafac35f067a3caf38b107c39  test021-in.nq
25b3cffff01dca8a204540d69ccd76b98e38d73dcae3cf7b28be4b8f16495f5d  test024-in.nq
25b3cffff01dca8a204540d69ccd76b98e38d73dcae3cf7b28be4b8f16495f5d  test025-in.nq
25b3cffff01dca8a204540d69ccd76b98e38d73dcae3cf7b28be4b8f16495f5d  test026-in.nq
25b3cffff01dca8a204540d69ccd76b98e38d73dcae3cf7b28be4b8f16495f5d  test027-in.nq
25b3cffff01dca8a204540d69ccd76b98e38d73dcae3cf7b28be4b8f16495f5d  test028-in.nq
25b3cffff01dca8a204540d69ccd76b98e38d73dcae3cf7b28be4b8f16495f5d  test029-in.nq
2d36644468c874782cf4503cb5118a17bd4f47c7a259441c51037252ca512c81  test048-in.nq
2ef259a336d63af1c74709b8038423a9113e61ed209caac495688cb0661c3af7  test005-in.nq
2f2e9f285cbacbde8231b320c415fb8324e848edc5271faa74762e21c0626c9a  test007-in.nq
39b9a77aa2e0cd3281da6aaeb6857b7e0422abebdee91031c9acaf4cd3c865f5  test002-in.nq
3b3f499873c5cdedc736fce5d9bb0491ae3975918648cdd7b240e636675d63b1  test053-in.nq
4165bc11409c53197034a62dd5a9a6d3262194278727172aacd41e315b405e8a  test052-in.nq
4789ed601eb78ee741e43a59dff2ddcccecf1cbe3c374657efd3892cb57619eb  test020-in.nq
63a9e314f71786bd1080f0bb3f2409c773b0ea475345cb9a34285c32632c40a1  test014-in.nq
6a308906cc1cbbb429fbecffaeaeb7a7eaa47c6df0eb6eb90be3a329c674786c  test011-in.nq
7b92692c80e37daab8419ad58d03f759e6b37eef97d7c5f6025db097c6ee784c  test057-in.nq
824724a357c737f10e6ec8ccc4d270e5e5fe7a6470764805d6562026ab2c8551  test022-in.nq
85d43631de82ca6736ef1bf81c0b1c36cefb971bbcfb501f59058e6f8221dd4e  test023-in.nq
a5ce20a1cf522b457da97c38af102213ff87a3c2d5e5e5d7b1975daf03bd8441  test044-in.nq
a61d66ca173f41c778119d3b324af1287c16912081245c896c3c6aff28d73acb  test009-in.nq
a71e6b5bd0aa0ae88a2d939e29f2da2999caf68d2ac2251c5186b1da077fb485  test012-in.nq
ad7113aacb2e743b3c0d593a1f88e5ea3b430841db994afaeec43cdd9d5ea2ae  test008-in.nq
b1ab8fd2005a5c4946ee551ca0f55b5d38a596de52e8a176955ea0d4924e27a1  test050-in.nq
b593334f26771ac5a191dff93277d548389480716c5d309a2bfc7f5cb5ff7a9a  test018-in.nq
ba6e6e8372401821a1b485de34a9bf1abfe8d53c7edbe84474ec1674c2959998  test040-in.nq
ba6e6e8372401821a1b485de34a9bf1abfe8d53c7edbe84474ec1674c2959998  test041-in.nq
ba6e6e8372401821a1b485de34a9bf1abfe8d53c7edbe84474ec1674c2959998  test042-in.nq
be35e88b98af9a6281afcd03abc529d4dc786c1b0acf1271e8b0e111f6ba8ec3  test003-in.nq
be35e88b98af9a6281afcd03abc529d4dc786c1b0acf1271e8b0e111f6ba8ec3  test031-in.nq
be35e88b98af9a6281afcd03abc529d4dc786c1b0acf1271e8b0e111f6ba8ec3  test032-in.nq
c0b846d5a8839beecaf07d024a0dfeff84d2668c131ea7476ef593cb603bf3f9  test006-in.nq
c156494ed20d3ee93e15957e891f01085e0021895211c45992c3aad647b36011  test056-in.nq
c6099190ee89cb89e462f52ceca8fcf2a7a436b4f0eb13b409891b5718bc86fb  test013-in.nq
cbefa8f496dca1e5385e51d5b5f4a9599d6e3917d9c44f4849bbd3c78c5e5e54  test047-in.nq
d515e0ba249e7ead148582812d8feb155588f18389c36fccfc52b42dfe1d9713  test033-in.nq
d515e0ba249e7ead148582812d8feb155588f18389c36fccfc52b42dfe1d9713  test034-in.nq
d68dfd5e1aa3496f0cba562a70f0db9bc9ee101f7d380d7520944d005a3ef054  test046-in.nq
d7256d7dcf24ac1cdb5264f6c59df9615f8e4e3c960988d059e0f036b721d63d  test055-in.nq
dda9b72dd2139928b9f405f050fd630971a0a9338b9b2499ff0edc94fa333750  test004-in.nq
e0096385a66b5cba870f4739a2585122fc5518b30d33dcbe05a6e1bf3925aaf4  test038-in.nq
e029d3e161995dccd37a1939720a9271bf9fafdee7efb000ba30b7c1dcfd5199  test030-in.nq
e29c9a3eba1601df7200a60b6ed8498ff8ef90633b71f4da10de3e7745a4a39e  test039-in.nq
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  test001-in.nq
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  test015-in.nq
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  test049-in.nq
f1780ba013f047d7c64c036c7a5557b2e0c6e8dba92273afd4ca956035d04c91  test016-in.nq
fd20aebf8142fcffc0dd8007b63156bd6c1d6d9535dfb407d28ab6136c5d018d  test054-in.nq
fea31b5799c6be3d1b996139671484e83fd7619d2137b0ee9e99d38c21832f1c  test045-in.nq
ffdafd76e01613eda867a1a945f7c5de23846ffb760ff7c55ca01a822aa73306  test019-in.nq
```

Doing the same on the current directory is, of course, different:

```
04e8e2f56462071ceaae7979f9c2ca4ac7e8978eba8fcad2ee39a4deae714749  test048-in.nq
07c504f3d95395090c72de805fc7eb90b0bae73d76922f9f94212e55a4180dc2  test060-in.nq
0b35a842886c838d5bb44bdf77c293974db401a23df3cfef0ea133a40ee18d96  test051-in.nq
1fcc2848b4ff46225aaed2233347a3e2f5977e0d1a46f9fc8334b15fc1a7248f  test043-in.nq
217f48105f01e5ae0478d727134c539435a168aa158937ee45a073a1bbb15913  test059-in.nq
24247d6489a07f5da7efd55aa06cbf46eec25845c936400ec04f67fdc19f56e8  test061-in.nq
264e35f5e00fbb03521485d060deb6f5b0ca60cdc1c399604c77c5bb19334225  test045-in.nq
28cbc072440b38b50a67a9eac605cf463e9342f15907743bf9e51fc244af74f1  test004-in.nq
29261445706454f9bbdd88b43f562f971e86cf45b5461be623d8ddb07d0f03a7  test022-in.nq
2f2e9f285cbacbde8231b320c415fb8324e848edc5271faa74762e21c0626c9a  test007-in.nq
358cb762f73966d0bbadb647dfd603089ddc655d66f10a2d9cbfbe66dfcf04bd  test057-in.nq
37cbd9ca6ee266eb1ba8fa9626fe57a70ba964ba2b58b0a1c2e2513f367756f3  test035-in.nq
37cbd9ca6ee266eb1ba8fa9626fe57a70ba964ba2b58b0a1c2e2513f367756f3  test036-in.nq
37cbd9ca6ee266eb1ba8fa9626fe57a70ba964ba2b58b0a1c2e2513f367756f3  test037-in.nq
39b9a77aa2e0cd3281da6aaeb6857b7e0422abebdee91031c9acaf4cd3c865f5  test002-in.nq
4165bc11409c53197034a62dd5a9a6d3262194278727172aacd41e315b405e8a  test052-in.nq
42adcd42e748b86bc801a84d12806295f40da4ce120fe362ab2ed1cefb5ca060  test044-in.nq
4789ed601eb78ee741e43a59dff2ddcccecf1cbe3c374657efd3892cb57619eb  test063-in.nq
4b94e151891c27978489b564eae1fb2ec8aa6d128335bd4b565c9e5fc7c0e3b5  test054-in.nq
563d440138a2e91ffbf057b27844445cdb40e316def642b94d17f67e4caed904  test058-in.nq
5b028131140bb7ef54febd65b45180f17416956beb937d4ff5b152e75f3f0449  test024-in.nq
5b028131140bb7ef54febd65b45180f17416956beb937d4ff5b152e75f3f0449  test025-in.nq
5b028131140bb7ef54febd65b45180f17416956beb937d4ff5b152e75f3f0449  test026-in.nq
5b028131140bb7ef54febd65b45180f17416956beb937d4ff5b152e75f3f0449  test027-in.nq
5b028131140bb7ef54febd65b45180f17416956beb937d4ff5b152e75f3f0449  test028-in.nq
5b028131140bb7ef54febd65b45180f17416956beb937d4ff5b152e75f3f0449  test029-in.nq
5d06a36ad4ef08f377b1e93ad18e84a55622fe3a1250f2aa1b53b724c3f5c8ce  test055-in.nq
5e4c3868caea74c1e744d9f43c0cfd1419782889d9abf30660ce8c41708f4b23  test053-in.nq
63a9e314f71786bd1080f0bb3f2409c773b0ea475345cb9a34285c32632c40a1  test014-in.nq
6a308906cc1cbbb429fbecffaeaeb7a7eaa47c6df0eb6eb90be3a329c674786c  test011-in.nq
709fa955675ac554ec9151f0d7bdb663e729309c54d0362f7e51120164e215ec  test010-in.nq
732c70942f58e97e6edc7388ce4b72f08953d288e75c3d9974fda9919c5d9e0f  test023-in.nq
76bb55efbeaf4d52f8034abf1cd63f51572b8a65799f39dd8b381d9d477f64fd  test017-in.nq
821da5dc0667b2045b7da6f3fd2dec35459bcf2440a0fb7d8cb58851b9f7110f  test033-in.nq
821da5dc0667b2045b7da6f3fd2dec35459bcf2440a0fb7d8cb58851b9f7110f  test034-in.nq
8623e57aee3fad03ea58c1f6df8e55772cf545b28b4cc38656c3e25f1cdbf4b9  test021-in.nq
a61d66ca173f41c778119d3b324af1287c16912081245c896c3c6aff28d73acb  test009-in.nq
a652e02f2804f5c47a1930deb9359f27f8fffc8aafcfbc6ace3303d47289d72f  test039-in.nq
a71e6b5bd0aa0ae88a2d939e29f2da2999caf68d2ac2251c5186b1da077fb485  test012-in.nq
a98fc435375960207345c50915df91f6f6f84f2b572148e5ee5d30afc626bf5e  test050-in.nq
ab9c1c6f6f329213fec62dfebd812e38494e1b12a80be6a692d8b066cb4654e4  test062-in.nq
ad7113aacb2e743b3c0d593a1f88e5ea3b430841db994afaeec43cdd9d5ea2ae  test008-in.nq
ae1204113c0184406cf252dd5cc90a6013dbb82d352a15f6e67ca3c3d7a81243  test018-in.nq
bb386ab848bad23ae94ba7f6e4705d2f5d4244dc8b235e35f59d575af344c603  test019-in.nq
c03038693a31ffc229b93eca5f6d3aa2081067713e9e990dacb712ace14d32d7  test046-in.nq
c0b846d5a8839beecaf07d024a0dfeff84d2668c131ea7476ef593cb603bf3f9  test006-in.nq
c1c1b191514bd11be294de2e9d66f4cf709b74c176d62c4431923c25d66da7d8  test040-in.nq
c1c1b191514bd11be294de2e9d66f4cf709b74c176d62c4431923c25d66da7d8  test041-in.nq
c1c1b191514bd11be294de2e9d66f4cf709b74c176d62c4431923c25d66da7d8  test042-in.nq
c2b7f81e9b6035dd24ba6bbe167e0f2470eed7bef2ba1c27a18b501ca3669e76  test038-in.nq
c6099190ee89cb89e462f52ceca8fcf2a7a436b4f0eb13b409891b5718bc86fb  test013-in.nq
c79a92bb74bd179033d2cc93068f7984933e081b07fc2313ed22f98b4dea14a4  test003-in.nq
c79a92bb74bd179033d2cc93068f7984933e081b07fc2313ed22f98b4dea14a4  test031-in.nq
c79a92bb74bd179033d2cc93068f7984933e081b07fc2313ed22f98b4dea14a4  test032-in.nq
cacaba7d18d2bbdd4c9d02642df456c5875b86fd89a70606a9e7f5f90ddbabdc  test016-in.nq
cc5cd85b4efe7c21dd95ed303a4b34bdb6c2a200c77588d0fbf0ad9d077ee47f  test005-in.nq
d8c0f19453eee00b18ac10f7167646634c0a95cc4439a5d1b2483f98a409486e  test047-in.nq
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  test001-in.nq
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  test015-in.nq
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  test049-in.nq
e7f721c63632f55a0d3bfd3b522d79c73b59f95a07e8afc277292684fba47160  test056-in.nq
ea1ef63c6f15f34360e4771681ef524a8acb4efb1eeb6c8783d5f161b3ba167f  test030-in.nq
fdc56ad22cbe5f590da7b7bd537d57b3bbc072f0aebb35c04a9d620344062cfb  test020-in.nq
```

The original repo (first commit with test inputs) has 57 input files, and we now have 63.

After de-duping, the original repo has 43 unique inputs and ours has 49, so it looks like the situation is unchanged from the first commits.

**Comment by yamdan** [comment]
@gkellogg By the way, the current `mk_manifest.rb` seems to require haml v5.2.x (not the latest). The latest haml v6.0.x changed its interface (according to their [changelog](https://haml.info/docs/yardoc/file.CHANGELOG.html#section-7)) that caused an error when I tried at first. I am not good at ruby so would like to ask you whether and which part we should patch the ruby script.

**Comment by gkellogg** [comment]
> I found the original JSON-LD version of the test cases in old documents, such as "Normalization tests" at https://dvcs.w3.org/hg/json-ld/raw-file/default/test-suite/, and some JSON-LD implementations like https://github.com/linkeddata/gojsonld/tree/master/test_files, etc. Although it is only up to test057 and it seems to be the tests for URGNA2012, it still helps explore the original intent of the test cases. I am now preparing a PR based on this.

Good to know, I think there’s another issue on the history of the effort that we can reference this in.

**Comment by gkellogg** [comment]
> @gkellogg By the way, the current `mk_manifest.rb` seems to require haml v5.2.x (not the latest). The latest haml v6.0.x changed its interface (according to their [changelog](https://haml.info/docs/yardoc/file.CHANGELOG.html#section-7)) that caused an error when I tried at first. I am not good at ruby so would like to ask you whether and which part we should patch the ruby script.

Thanks for looking at this; I hadn’t noticed the haml update; it will affect some more things, but I’ll look at this specific use tomorrow.

**Comment by yamdan** [comment]
> Good to know, I think there’s another issue on the history of the effort that we can reference this in.

Thanks, I guess that you mean the issue #19 by "another issue".

**Comment by gkellogg** [comment]
> @gkellogg By the way, the current `mk_manifest.rb` seems to require haml v5.2.x (not the latest). The latest haml v6.0.x changed its interface (according to their [changelog](https://haml.info/docs/yardoc/file.CHANGELOG.html#section-7)) that caused an error when I tried at first. I am not good at ruby so would like to ask you whether and which part we should patch the ruby script.

For the time being, only use version 5.2.2 of the haml gem. There are other elements of the ecosystem that depend on this, and the updates in Haml 6.0 break RDFa generation, which is still used (e.g., in mk_vocab.rb).

I'll spend more time on this later. I could install a Gemfile to fix gem versions, but that can only create update headaches in the future.

```
gem install haml --version 5.2.2
```

You can also `gem uninstall haml --version 6.1.1` (or whatever version you have installed greater than 5.
