### ISSUE TITLE
Naming the algorithm (Bike-shedding danger ahead!)

### ISSUE THREAD

**Issue by iherman** [w3c/rdf-canon#87]
I must admit I hate the name "URDNA2015". I never remember what URDNA stands for (I always associate it with some weird gene...) and the 2015 is irrelevant.

Shouldn't we come with a simpler name? We could simply call it RCH, for example and, if we need it, we can use the "usual" W3C versioning habit of calling it RCH 1.0.

Just a thought. But it is still time to make this change.

**Comment by gobengo** [comment]
Is it 'rdf canonicalization' and 'rdf hashing' (which implicitly might involve canonicalization) as too separate things?

RC
RH

together the techniques are RCH (et al)

I have been confused about whether the `2015` is an intentional indicator of 'be careful relying on this'

**Comment by iherman** [comment]
> Is it 'rdf canonicalization' and 'rdf hashing' (which implicitly might involve canonicalization) as too separate things?
> 
> RC RH
> 
> together the techniques are RCH (et al)

Algorithmically, you are right. On the other hand, "RC" and "RH" are fairly short and could be mixed up with other possible meaning of these abbreviations, which is always a bit dangerous. 

We also decided, on our last call, to issue only one Recommendation document that would incorporate both the canonicalization and hashing.

But we could also use RDF-C and RDF-H if we want to separate the two. or RDFC and RDFH, respectively. All these are easy to remember and that is important.

**Comment by TallTed** [comment]
RDFDC = RDF Dataset Canonicalization
RDFDH = RDF Dataset Hashing
RDFDCH = RDF Dataset Canonicalization & Hashing

I think two-letter acronyms or nicknames are too short and overloaded. Three-letter *might* not be terribly overloaded. The longer ones above are much less likely to be overloaded (but worth verification).

**Comment by iherman** [comment]
WG resolution on 2023-06-07: RDFC-1.0 it is!

**Comment by gkellogg** [comment]
Closed via #116.
