### ISSUE TITLE
Should multiformats refer to URDNA or URDCA?

### ISSUE THREAD

**Issue by gobengo** [w3c/rdf-canon#88]
[there is a PR](https://github.com/multiformats/multicodec/pull/261) that contributed a reference to some of this in multiformats/multicodec

the pr title says 'urdna' but the pr [added the name using 'urdca'](https://github.com/multiformats/multicodec/pull/261/files#diff-bf5b449ed8c1850371f42808a186b5c5089edd0025700505a6b8f426cd54a6e4R486). Which is more... canonical.... normal.... whatever. What should we put it in the multicodec `name` column? :)

I imagine this decision has editorial implications for the spec itself? [It still says](https://w3c.github.io/rdf-canon/spec/) 'urdna2015' quite a bit and does not contain 'urdca'. So why should multibase say 'urdca'?

Relates to:
* https://github.com/w3c/rdf-canon/issues/87

**Comment by gobengo** [comment]
@msporny said

> 

There is a debate raging over what we should call it. Traditionally, we used "n" to mean "normalization"... but it's generally accepted now that we should've said "canonicalization" since it's a more accurate description of what's happening. Thus, the "urdca" vs. "urdna" distinction. This is currently being discussed in the W3C RDF Dataset, Canonicalization, and Hashing Working Group (note that we didn't call it the "normalization" working group).

https://github.com/multiformats/multicodec/pull/261/files#r1155026420

Is this issue appropriate here on rdf-canon, or in another issue tracker?

**Comment by philarcher** [comment]
Group resolution 2023-06-07. The name is RDFC-1.0

**Comment by gkellogg** [comment]
Closed via #116.
