### ISSUE TITLE
Figure out RDH process flow and additional outputs

### ISSUE THREAD

**Issue by yamdan** [w3c/rdf-canon#92]
Following the TPAC joint meeting discussion and subsequent issue w3c/rch-rdc#4 raised by @pchampin, I think it could be a good entry point to determine the whole possible process flow from an RDF document to an RDF hash value. Furthermore, we could consider additional flows to get the other types of outputs besides a simple hash value, which is helpful for ZKP-friendly multi-message signatures such as [BBS+](https://datatracker.ietf.org/doc/draft-looker-cfrg-bbs-signatures/).

The blue-colored parts in the following figure show my current understanding of calculating a hash value from an RDF document:
![20220927_rch](https://user-images.githubusercontent.com/13946589/192448700-6519c39a-2909-467a-8c36-98b542b84cf1.png)
We start with an **RDF document**, such as a JSON-LD document describing that Alice knows Bobby.
We can **deserialize** the document to obtain an abstract **RDF dataset**, an unordered set of RDF graphs/triples.
Using **RDF canonicalization algorithms** (to be standardized in this WG), the dataset can be canonicalized into a **canonicalized RDF dataset**, where all the blank nodes are deterministically labeled.
Here I assume that the canonicalized RDF dataset is an abstract dataset aligned with the WG charter, related to Issue #4.
We can **serialize** the canonicalized RDF dataset, with some whitespace normalizations, into an N-Quads document, which I temporarily name as a **semi-canonicalized RDF document**, where the order of RDF quads is not determined yet.
Then, we can lexicographically **sort** it to get a **canonicalized RDF document**, where all the blank node identifiers and the order of quads are deterministically generated from the input RDF document.
The canonicalized RDF document can be **hashed** using an appropriate hash function to obtain a **canonicalized RDF hash value**.
The above flow describes my current understanding of a simple RDF hashing, where we could revise some terminologies later.

Besides the blue-colored main flow, we can also discuss other valuable branches, especially for multi-message signature schemes like BBS+.
For example, [LDP-BBS2020](https://w3c-ccg.github.io/ldp-bbs2020/) splits the canonicalized RDF document into statements, regarded as messages to be signed by the BBS+ signature scheme. This statement-wise splitting with BBS+ allows us to do statement-wise selective disclosure.
Furthermore, a term-wise encoding, used in our modified version of LDP-BBS2020 ([paper](https://sako-lab.jp/download.php?article=ssr2022_proceedings_dan.pdf) / [demo](https://zkp-ld.org/)) mentioned in TPAC meeting by @OR13, splits the canonicalized RDF document into RDF **terms** to enable term-wise selective disclosure and predicate proofs with BBS+.
I wonder if these canonicalized RDF statements/terms could also be worth considering as the extended outputs of the RDF "hash" in this WG.

**Comment by peacekeeper** [comment]
The RCH WG has passed a resolution that it will work on a single Rec Track document "RDF Dataset Canonicalization" here in this repository.

Therefore I transferred this issue from https://github.com/w3c/rch-rdh/issues/2 to this new location here (old issue URL redirects to here).

See here for the WG resolution: https://www.w3.org/2023/03/29-rch-minutes.html#ResolutionSummary
