### ISSUE TITLE
Add diagram for the algorithm

### ISSUE THREAD

**Issue by philarcher** [w3c/rdf-canon#98]
Although Issue #92 is closing, the diagram is widely seen as useful and should be included in the spec. See also the WG [resolution on 2023-05-03](https://www.w3.org/2023/05/03-rch-minutes.html#ResolutionSummary)

**Comment by davidlehn** [comment]
One thing to consider is how precise the diagram needs to be with respect to data structures.  The "JSON-LD" and "N-Quads" blocks are defined, but the others are intermediate internal formats, or perhaps not well defined (yet).  Should make it clear which ones are examples but not required representations.

- The dataset blocks look simplified.  Would datatype or lang usage change them?
- The `Canonical RDF Statements` block might have newlines per statement.  (Not sure how others do it, but Digital Bazaar's code serializes the newlines per statement.)
- The `Canonical RDF Terms` block looks LISPy, but other formats are possible, such as the RDF.js spec that their whole tool ecosystem uses: https://rdf.js.org/data-model-spec/

**Comment by yamdan** [comment]
@davidlehn Thanks, I updated the diagram below with the following changes:
- simplify example
- rewrite dataset blocks as RDF/JS data structures
- rename each component to align with the current specification
- add blank node map to the normalized dataset
- remove unnecessarily complicated parts (i.e., term-wise encoding)

![20230509_rch](https://user-images.githubusercontent.com/13946589/237006016-200a0382-a459-4376-822f-555e331e0c6f.svg)

Also I uploaded the editable diagram to Google Slides. Feel free to update it (I have my own backup slides.)
https://docs.google.com/presentation/d/1l5R7ZjY89wMLQrJDE6LZ66is3RaMk0bnrdS3qO9aGbw/edit?usp=sharing

**Comment by seabass-labrax** [comment]
@yamdan, do you mind if I have a go at writing the diagram in [PlantUML](https://plantuml.com/) or[Mermaid](https://mermaid.js.org/)? It would be nice to have this in Git defined by text.

**Comment by yamdan** [comment]
@seabass-labrax Thank you, that would be very helpful. I could also work on it from next week onwards, but this week is a bit difficult for me.

**Comment by yamdan** [comment]
I simplified the diagram and updated the terminology to match the latest specifications.
I'm still not familiar with how to draw such diagrams with mermaid or plantUML...

![20230509_rch](https://github.com/w3c/rdf-canon/assets/13946589/d7360bd6-492b-472c-9005-1c337cd49857)

**Comment by gkellogg** [comment]
Do you have the source location that can be added to the spec (as a comment) for future editing? Can you add this into the spec the way other SVG has been added? I can help with this, if necessary.

**Comment by yamdan** [comment]
@gkellogg Sure, I will prepare it later.

**Comment by seabass-labrax** [comment]
> @yamdan, do you mind if I have a go at writing the diagram in [PlantUML](https://plantuml.com/) or [Mermaid](https://mermaid.js.org/)? It would be nice to have this in Git defined by text.

As discussed in today's RCH WG meeting, we'll use your SVGs directly rather than trying to replicate them with PlantUML.
